### ISSUE TITLE
tools.jar missing

### ISSUE THREAD

**Issue by kungfooman** [angular/clutz#818] opened 2018-12-26 02:19 UTC
Hi, I get this error for `gradle build installDist`:

```
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not find tools.jar. Please check that /usr/lib/jvm/java-11-openjdk-amd64 contains a valid (and compatible) JDK installation.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Quoting from https://dzone.com/articles/jdk-9-is-the-end-of-the-road-for-some-features

`
Additional details on the removal of these JARs and anticipated effects of these removals can be found in Java 9 completely changes JDK directory layout and drops tools.jar, How Java 9 And Project Jigsaw May Break Your Code, and Prepare for JDK 9. No one argues that it was well-advertised that these APIs were not intended for external use, but "some popular libraries make use of non-standard, unstable, and unsupported APIs that are internal implementation details of the JDK and were never intended for external use."
`

Which Java version is needed to compile this and why depend on deprecated JDK internal stuff in the first place?

**Comment by kungfooman** [comment] 2018-12-26 23:15
Got it to work on Ubuntu by installing Java 8 and node 10:

```
apt-get install openjdk-8-jdk
apt-get install unp
wget https://nodejs.org/dist/v10.15.0/node-v10.15.0-linux-x64.tar.xz
unp node-v10.15.0-linux-x64.tar.xz
PATH=$PATH:/root/node-v10.15.0-linux-x64/bin
```

**Comment by mprobst** [comment] 2019-01-02 10:14
I think this is just a dupe of #819, moving over to there.

**Closed by mprobst** 2019-01-02 10:14 UTC
