### ISSUE TITLE
Test failure on Mac os

### ISSUE THREAD

**Issue by jollytoad** [angular/clutz#594] opened 2017-11-27 23:29 UTC
I'm trying to build clutz/gents, but it seem to be failing on a single test...

> com.google.javascript.clutz.DeclarationSyntaxTest > testDeclarationUsage FAILED
    java.lang.AssertionError: tsc exited abnormally with code 1
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(6,18): error TS2503: Cannot find namespace 'alias'.
    src/test/java/com/google/javascript/clutz/reserved_var_names.d.ts(10,18): error TS2503: Cannot find namespace 'alias'.
        at org.junit.Assert.fail(Assert.java:88)
        at com.google.javascript.clutz.DeclarationSyntaxTest.runChecked(DeclarationSyntaxTest.java:130)
        at com.google.javascript.clutz.DeclarationSyntaxTest.doTestDeclarationUsage(DeclarationSyntaxTest.java:119)
        at com.google.javascript.clutz.DeclarationSyntaxTest.testDeclarationUsage(DeclarationSyntaxTest.java:101)
>
> 165 tests completed, 1 failed

java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

Gradle 4.3.1

$ ./node_modules/typescript/bin/tsc
Version 2.4.2

Any ideas?

**Comment by rkirov** [comment] 2017-12-13 00:38
Hmm, no idea. Also kinda odd that only this one file err, I dont see anything special there.

**Comment by jvilk** [comment] 2018-02-09 17:55
While I agree that this is an odd error, I am having the same problem on Mac OSX. It's possible that this is a platform-specific TypeScript bug. I tried to extract the exact `tsc` command that Clutz is running here, but must've missed something because the command I extracted worked when manually run.

A workaround is to comment out the `testDeclarationUsage` test in `src/test/java/com/google/javascript/clutz/DeclarationSyntaxTest.java` so the `installDist` command completes successfully.

**Comment by rkirov** [comment] 2018-05-08 23:27
I finally reproduced this locally (thought it keeps on passing on Travis).

The issue is that TypeScript compiler itself had a bug where if `reserved_var_names_usage.ts` is passed to tsc before `reserved_var_names.d.ts` this error happens. I added a debug logging of how we call tsc, so you can see if this is the case for you. 

I was about to file a bug with TS team about this, because as far as I know `tsc` arguments order should never matter, but it appears to be fixed in typescript@next. If you want to get unblocked on building clutz, just use that version of tsc in your local node_modules.

**Closed by rkirov** 2018-05-08 23:27 UTC
