### ISSUE TITLE
Export is Empty

### ISSUE THREAD

**Issue by khatamnejad** [angular/clutz#350] opened 2016-09-22 19:18 UTC
I converted some .js files into TypeScript using the tool; However in the generated files the `export` statement exports and empty object while there used to be a `provide` statement in the original .js.

I see the `goog.scope` is not removed in the TypeScript file ([bug](https://github.com/angular/clutz/issues/349)); I guess that might have confused the converter.

**Comment by khatamnejad** [comment] 2016-09-22 21:39
Update: I removed the `goog.scope` block and the `export` statement is more meaningful now however it not create any `module`s for my class.

**Comment by gmoothart** [comment] 2016-09-22 21:50
Can you add some example input/output?

**Comment by khatamnejad** [comment] 2016-09-22 22:05
My original .js File:

```
goog.provide('a.b.c.d.MyClass');
goog.provide('a.b.c.d.MyClass.MySubType');


goog.scope(function() {


/**
 * A static class.
 */
a.b.c.d.MyClass = {};
var MyClass = a.b.c.d.MyClass;


/**
 * A sub type.
 *
 * @typedef {{
 *   p: string
 * }}
 */
a.b.c.d.MyClass.MySubType;

...

});

```
Converted .ts file:

```
import SomeOtherClass from 'goog:a.b.d.SomeOtherClass'; // from //[path]
export {};

goog.scope(function() {
/**
* A static class.
*/
a.b.c.MyClass = {};
let MyClass = a.b.c.MyClass;
/**
*A sub type.
*@typedef {{
*  p: string
*}}
*/
a.b.c.d.MyClass.MySubType;

...

});
```

**Comment by dpurp** [comment] 2016-10-11 21:40
I'm going to close this issue in favor of #349.  

The root of the problem is that gents is not yet aware of `goog.scope`, so any exports exported from goog.scope will not exported.

**Closed by dpurp** 2016-10-11 21:40 UTC
Labels: gents
